/** 
 * jQuery validate integration demo.  This is a demonstration of integrating
 * LeadSpend Email Validation info a form.  For more information about these
 * customizations, please check out the README file found in the root folder.
 */
$(document).ready(function(){
	//Bind jQuery Validate to the form
	$("#ID_OF_FORM").validate({
		//override the default onkeyup validation to prevent it on specific fields
		onkeyup: function(element) {
			
			if ($(element).attr('name') != $(".LeadSpendEmail").attr("name")) {
				$.validator.defaults.onkeyup.apply(this,arguments);
			}
		},
		//override the default invalidHandler to help with form submission
		invalidHandler: function(form, validator) {
			LeadSpend.invalidHandler(form, validator);
		},
		//override the default messages for the LeadSpendEmail rule as applied to
		//the EMAIL_FIELD_NAME field
		rules:{
			EMAIL_FIELD_NAME:{
				"LeadSpendEmail":{
					//a message can be passed as a string
					validityPendingMessage: "Validation in progress...",
					
					//or a message can be generated by a custom function
					denyAddressMessage: function(validity){
						if (typeof validity != "undefined"){
							return "This email address is "+validity.result+". Please use another.";
						}
						return "Invalid address.";
					}
				}
			}
		}
	});
}); 